FanfingTasticAlias <c-f>t ~
FanfingTasticAlias <c-f>i !
FanfingTasticAlias <c-f>o @
FanfingTasticAlias <c-f>h #
FanfingTasticAlias <c-f>d $
FanfingTasticAlias <c-f>p %
FanfingTasticAlias <c-f>e ^
FanfingTasticAlias <c-f>a &
FanfingTasticAlias <c-f>x *
FanfingTasticAlias <c-f>b (
FanfingTasticAlias <c-g>b )
FanfingTasticAlias <c-f>B {
FanfingTasticAlias <c-g>B }
FanfingTasticAlias <c-f>c {
FanfingTasticAlias <c-g>c }
FanfingTasticAlias <c-f>r [
FanfingTasticAlias <c-g>r ]
FanfingTasticAlias <c-f>n <
FanfingTasticAlias <c-g>n >
